### ISSUE TITLE
"facebook-bug" appearing as only returned result

### ISSUE THREAD

**Issue by thetwosents** [tryolabs/social-media-scraper#4]
When running with TechCrunch as the URL just for first run testing, I'm receiving this issue: 
<img width="269" alt="Screen Shot 2019-06-29 at 2 34 42 PM" src="https://user-images.githubusercontent.com/3770257/60388720-17a73600-9a7b-11e9-9981-2a86c530366c.png">

**Comment by brunosegiu** [comment]
Fixed here: https://github.com/tryolabs/social-media-scraper/commit/5c6a69983689b2e6e917a7156862be02ee9bd9f8

Thanks for the heads up
